### ISSUE TITLE
Request - Create a Flatpak package for Linux

### ISSUE THREAD

**Issue by libreajans** [cmpilato/thotkeeper#51]
Hi, Flatpak becomes more and more popular among Linux users. I couldn't find any package for your application on Ubuntu repositories or Flathub.org

Could you create a Flatpak package?

**Comment by cmpilato** [comment]
This project hasn't concerned itself with the details of packages, preferring to make the ThotKeeper source code available for external package maintainers to deliver as they wish.  That said, if a knowledgeable contributor wanted to donate the tooling (perhaps even via a Github Action such as this quick search result: https://github.com/marketplace/actions/flatpak-builder) to make this happen, I'd certainly consider it.
